#!/bin/bash
# This `DEBIAN/preinst` script is run pre-installation

# Comprobamos si el directorio raíz se ha quedado con caché
echo "Checking if there is a previous version of the symbolic link installed..."
SYMLINK=/usr/local/bin/power-monitor-d
if [ -L ${SYMLINK} ] ; then
   if [ -e ${SYMLINK} ] ; then
      echo "[preinst] Good link installed, removing..."
      rm -r "$SYMLINK"
      echo "[preinst] Removed"
   else
      echo "[preinst] Broken link, removing..."
      rm -r "$SYMLINK"
      echo "[preinst] Removed"
   fi
elif [ -e ${SYMLINK} ] ; then
   echo "[preinst] Not a link, removing..."
   rm -r "$SYMLINK"
   echo "[preinst] Removed"
else
   echo "[preinst] Missing"
fi

echo "Checking if there is a previous version of the symbolic link installed..."
SYMLINK=/usr/share/power-data
if [ -L ${SYMLINK} ] ; then
   if [ -e ${SYMLINK} ] ; then
      echo "[preinst] Good link installed, removing..."
      rm -r "$SYMLINK"
      echo "[preinst] Removed"
   else
      echo "[preinst] Broken link, removing..."
      rm -r "$SYMLINK"
      echo "[preinst] Removed"
   fi
elif [ -e ${SYMLINK} ] ; then
   echo "[preinst] Not a link, removing..."
   rm -r "$SYMLINK"
   echo "[preinst] Removed"
else
   echo "[preinst] Missing"
fi
